#ifndef FIATSHAMIR_PROVER_H
#define FIATSHAMIR_PROVER_H

#include <vector>
#include "../utils.h"

using namespace std;
using namespace Utils;

class prover {
public:
	int k;                                               // Number of witnesses, security parameter
	int n;                                               // Modulo generated in setup
	int r;                                               // Random value generated by user
	vector<int> witnesses;                               // Witnesses generated in setup phase

	prover(int k, int n, vector<int> witnesses);
	prover(int k, int n, int r, vector<int> witnesses);
	int calculate_x();
	int calculate_y(vector<bool> toggles);
	map<string, string> serialise() const;
};


#endif //FIATSHAMIR_PROVER_H
